spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: ${SQL_SHOW:true}
    properties:
      hibernate:
        format_sql: ${SQL_FORMAT:true}
    open-in-view: false

  lifecycle:
    timeout-per-shutdown-phase: 30s

  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      fail-on-empty-beans: false

  servlet:
    multipart:
      max-file-size: 10MB

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: ${GITHUB_REDIRECT_URI:nalag://}
            scope:
              - user
              - repo
              - members
              - metadata
              - admin
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URL}
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile
  main:
    allow-bean-definition-overriding: true

jwt:
  secret-key: ${JWT_SECRET_KEY:he436dhh$^JhYHRHh5379p8t5ry655%U&^KJ%JU%U$}
  access_exp: ${JWT_ACCESS_EXP:7200}
  refresh_exp: ${JWT_REFRESH_EXP:86400}
  header: ${JWT_HEADER:Authorization}
  prefix: ${JWT_PREFIX:Bearer }

cloud:
  aws:
    s3:
      prefix: ${AWS_S3_PREFIX:/}
      bucket: ${AWS_S3_BUCKET:nalag-bucket/}
      base-image-url: ${AWS_S3_URL:/}
    region:
      static: ${AWS_S3_REGION:ap-northeast-2}
    stack:
      auto: false
    credentials:
      access-key: ${AWS_S3_ACCESS}
      secret-key: ${AWS_S3_SECRET}
