spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    show-sql: ${SQL_SHOW:true}
    properties:
      hibernate:
        format_sql: ${SQL_FORMAT:true}
    open-in-view: false

  lifecycle:
    timeout-per-shutdown-phase: 30s

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URL}
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile

jwt:
  secret-key: ${JWT_SECRET_KEY:he436dhh$^JhYHRHh5379p8t5ry655%U&^KJ%JU%U$}
  access_exp: ${JWT_ACCESS_EXP:7200}
  refresh_exp: ${JWT_REFRESH_EXP:86400}